<#
.SYNOPSIS
    Fabrication System Root Fixer
.DESCRIPTION
    Scans and fixes all Fabrication System instances in the specified root directory.
    Ensures all instances are properly configured and functional.
.NOTES
    Author: Raymond Demitrio Tel
    Version: 1.0.0
    Last Updated: 2025-12-13
#>

# Configuration
$rootPath = "D:\busineshuboffline CHATGTP\TOGETHERSYSTEMS- GITHUB\Nieuwe map (3)"
$logFile = Join-Path -Path $rootPath -ChildPath "FabricationRootFixer_$(Get-Date -Format 'yyyyMMdd_HHmmss').log"

# Start logging
Start-Transcript -Path $logFile -Force
Write-Host "Fabrication Root Fixer started at $(Get-Date)" -ForegroundColor Cyan
Write-Host "Root path: $rootPath" -ForegroundColor Cyan

# Function to write colored output
function Write-Status {
    param(
        [string]$Message,
        [string]$Status = "INFO"
    )

    $timestamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
    $statusMap = @{
        "INFO" = @{ Color = "White"; Prefix = "[INFO] " }
        "SUCCESS" = @{ Color = "Green"; Prefix = "[OK] " }
        "WARNING" = @{ Color = "Yellow"; Prefix = "[WARN] " }
        "ERROR" = @{ Color = "Red"; Prefix = "[ERROR] " }
    }

    $statusInfo = $statusMap[$Status]
    if (-not $statusInfo) { $statusInfo = $statusMap["INFO"] }

    $logMessage = "$timestamp $($statusInfo.Prefix)$Message"
    Write-Host $logMessage -ForegroundColor $statusInfo.Color
    Write-Output $logMessage
}

# Function to fix a single Fabrication System instance
function Repair-FabricationInstance {
    param(
        [string]$InstancePath
    )

    Write-Status "Processing instance: $InstancePath" "INFO"

    # 1. Ensure required directories exist
    $requiredDirs = @("Logs", "Reports", "Issues", "Fixes", "Config")
    foreach ($dir in $requiredDirs) {
        $dirPath = Join-Path -Path $InstancePath -ChildPath $dir
        if (-not (Test-Path -Path $dirPath)) {
            try {
                New-Item -ItemType Directory -Path $dirPath -Force | Out-Null
                Write-Status "Created directory: $dirPath" "SUCCESS"
            } catch {
                Write-Status "Failed to create directory $dirPath : $_" "ERROR"
                return $false
            }
        }
    }

    # 2. Check and fix module file
    $moduleFile = Join-Path -Path $InstancePath -ChildPath "FabricationSystem.psm1"
    if (-not (Test-Path -Path $moduleFile)) {
        try {
            @'
# Fabrication System Module
# Auto-generated by Fabrication Root Fixer

function Start-FabricationSystem {
    [CmdletBinding()]
    param(
        [ValidateSet('Active', 'Ruhestand')]
        [string]$Mode = 'Active'
    )
    Write-Host "Fabrication System started in $Mode mode at $(Get-Date)"
}

function Get-SystemStatus {
    [CmdletBinding()]
    param()
    return @{
        Status = "Operational"
        Timestamp = Get-Date
    }
}

Export-ModuleMember -Function Start-FabricationSystem, Get-SystemStatus
'@ | Out-File -FilePath $moduleFile -Encoding utf8 -Force
            Write-Status "Created module file: $moduleFile" "SUCCESS"
        } catch {
            Write-Status "Failed to create module file: $_" "ERROR"
            return $false
        }
    }

    # 3. Check and fix script file
    $scriptFile = Join-Path -Path $InstancePath -ChildPath "FabricationSystem.ps1"
    if (-not (Test-Path -Path $scriptFile)) {
        try {
            @'
# Fabrication System Main Script
# Auto-generated by Fabrication Root Fixer

# Import the module
$modulePath = Join-Path -Path $PSScriptRoot -ChildPath "FabricationSystem.psm1"
if (Test-Path $modulePath) {
    Import-Module $modulePath -Force
    Start-FabricationSystem -Mode Active
} else {
    Write-Error "Fabrication System module not found at: $modulePath"
    exit 1
}
'@ | Out-File -FilePath $scriptFile -Encoding utf8 -Force
            Write-Status "Created script file: $scriptFile" "SUCCESS"
        } catch {
            Write-Status "Failed to create script file: $_" "ERROR"
            return $false
        }
    }

    # 4. Check and fix module manifest
    $manifestFile = Join-Path -Path $InstancePath -ChildPath "FabricationSystem.psd1"
    if (-not (Test-Path -Path $manifestFile)) {
        try {
            $manifestContent = @"
@{
    ModuleVersion = '1.0.0'
    GUID = '$(New-Guid)'
    Author = 'Raymond Demitrio Tel'
    CompanyName = 'Fabrication Systems'
    Copyright = 'Copyright (c) 2025'
    Description = 'Fabrication System Module'
    PowerShellVersion = '5.1'
    RootModule = 'FabricationSystem.psm1'
    FunctionsToExport = @('Start-FabricationSystem', 'Get-SystemStatus')
    CmdletsToExport = @()
    VariablesToExport = @()
    AliasesToExport = @()
    PrivateData = @{
        PSData = @{
            Tags = @('Fabrication', 'System', 'Maintenance')
            LicenseUri = ''
            ProjectUri = ''
            ReleaseNotes = ''
        }
    }
}
"@
            $manifestContent | Out-File -FilePath $manifestFile -Encoding utf8 -Force
            Write-Status "Created module manifest: $manifestFile" "SUCCESS"
        } catch {
            Write-Status "Failed to create module manifest: $_" "ERROR"
            return $false
        }
    }

    # 5. Test the module
    try {
        $moduleName = (Get-Item $moduleFile).BaseName
        Import-Module $moduleFile -Force -ErrorAction Stop
        Write-Status "Successfully imported module: $moduleName" "SUCCESS"
        
        # Test basic functionality
        $status = Get-SystemStatus -ErrorAction Stop
        Write-Status "System status: $($status.Status)" "INFO"
        
        Remove-Module -Name $moduleName -Force -ErrorAction SilentlyContinue
        return $true
    } catch {
        Write-Status "Failed to test module: $_" "ERROR"
        return $false
    }
}

# Main execution
try {
    Write-Status "Starting Fabrication System Root Fixer" "INFO"
    Write-Status "Scanning directory: $rootPath" "INFO"

    # Find all Fabrication System instances
    $instances = @()
    
    # Look for module files
    $moduleFiles = Get-ChildItem -Path $rootPath -Filter "FabricationSystem.psm1" -Recurse -ErrorAction SilentlyContinue
    
    foreach ($file in $moduleFiles) {
        $instancePath = $file.Directory.FullName
        if ($instances -notcontains $instancePath) {
            $instances += $instancePath
        }
    }

    # If no instances found, create one in the root
    if ($instances.Count -eq 0) {
        Write-Status "No Fabrication System instances found. Creating new instance in root directory." "WARNING"
        $newInstancePath = Join-Path -Path $rootPath -ChildPath "FabricationSystem"
        $instances += $newInstancePath
    }

    # Process each instance
    $successCount = 0
    foreach ($instance in $instances) {
        Write-Status "`n=== Processing instance: $instance ===" "INFO"
        $result = Repair-FabricationInstance -InstancePath $instance
        if ($result) {
            $successCount++
            Write-Status "Successfully processed instance: $instance" "SUCCESS"
        } else {
            Write-Status "Failed to process instance: $instance" "ERROR"
        }
        Write-Status "=" * 80 "INFO"
    }

    # Summary
    Write-Status "`n=== Processing Complete ===" "INFO"
    Write-Status "Total instances processed: $($instances.Count)" "INFO"
    Write-Status "Successfully fixed: $successCount" "SUCCESS"
    Write-Status "Failed: $($instances.Count - $successCount)" -Status $(if (($instances.Count - $successCount) -gt 0) { "ERROR" } else { "SUCCESS" })
    Write-Status "Log file: $logFile" "INFO"

} catch {
    Write-Status "Fatal error: $_" "ERROR"
    Write-Status $_.ScriptStackTrace "ERROR"
} finally {
    Write-Host "`nFabrication Root Fixer completed at $(Get-Date)" -ForegroundColor Cyan
    Stop-Transcript
}