name: ostosos
version: '1.0.0'
summary: OSTOSOS Operating System
description: |
  A complete offline operating system with portal, manifest, formula farm, and more.

grade: stable
confinement: strict

apps:
  ostosos:
    command: desktop-launch $SNAP/usr/bin/chromium --app=file://$SNAP/index.html
    plugs:
      - desktop
      - desktop-legacy
      - wayland
      - x11

parts:
  ostosos:
    plugin: dump
    source: .
